export const MenuData = [
  {
    id: "00",
    text: "仪表盘",
    description: "",
    url: "/",
    iconCls: "AppstoreOutlined",
    role: [],
    activeName: "index"
  }, {
    id: "10",
    text: "动态代理",
    description: "",
    url: "/dynamic-residence",
    iconCls: "HomeOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "1001",
        text: "购买代理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "AccountBookOutlined",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "1002",
        text: "生成代理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "SendOutlined",
        role: [],
        activeName: "generateProxies"
      }, {
        id: "1003",
        text: "流量详情",
        description: "trafficDetails",
        url: "http://www.baidu.com",
        iconCls: "FundViewOutlined",
        role: [],
        activeName: "trafficDetails"
      }, {
        id: "1004",
        text: "订单",
        description: "historicalBilling",
        url: "http://www.baidu.com",
        iconCls: "FileSearchOutlined",
        role: [],
        activeName: "historicalBilling"
      }
    ]
  }, {
    id: "30",
    text: "不限量代理",
    description: "",
    url: "/unlimited-agency",
    iconCls: "AreaChartOutlined",
    role: [],
    activeName: "buyProxy",
    children: [
      {
        id: "3001",
        text: "购买代理",
        description: "说明2",
        url: "http://www.baidu.com",
        iconCls: "AccountBookOutlined",
        role: [],
        activeName: "buyProxy"
      }, {
        id: "3003",
        text: "订单",
        description: "说明2",
        url: "http://www.baidu.com",
        iconCls: "FileSearchOutlined",
        role: [],
        activeName: "unlimited_order"
      }
    ]
  }, {
    id: "20",
    text: "静态代理",
    description: "",
    url: "/static-residence",
    iconCls: "LineChartOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "2001",
        text: "购买代理",
        description: "说明2",
        url: "http://www.baidu.com",
        iconCls: "AccountBookOutlined",
        role: [],
        activeName: "static_buyProxy"
      }, {
        id: "2002",
        text: "IP详情",
        description: "说明2",
        url: "http://www.baidu.com",
        iconCls: "FundProjectionScreenOutlined",
        role: [],
        activeName: "IPdetail"
      }, {
        id: "2003",
        text: "订单",
        description: "说明2",
        url: "http://www.baidu.com",
        iconCls: "FileSearchOutlined",
        role: [],
        activeName: "static_order"
      }
    ]
  }, {
    id: "40",
    text: "静态代理管理",
    description: "",
    url: "#",
    iconCls: "ToolOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "4001",
        text: "静态资源配置",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "4002",
        text: "价格配置",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "4003",
        text: "接入节点配置",
        description: "接入服配置",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "4004",
        text: "测试账号开设",
        description: "为用户开设测试账号",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "4005",
        text: "正式账号开设",
        description: "为用户开设正式账号",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "4006",
        text: "已卖记录",
        description: "已卖静态代理记录",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "50",
    text: "订单管理",
    description: "订单及支付管理",
    url: "",
    iconCls: "SnippetsOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "5001",
        text: "订单列表",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "5002",
        text: "支付记录",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "60",
    text: "统计报表",
    description: "",
    url: "",
    iconCls: "BarChartOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "6001",
        text: "代理商流量消费日统计",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "6002",
        text: "用户流量消费日统计",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "6003",
        text: "子账号流量消费日统计",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "80",
    text: "用户管理",
    description: "",
    url: "",
    iconCls: "UserOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "8001",
        text: "代理商管理",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "8002",
        text: "用户管理",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "8003",
        text: "子账号管理",
        description: "",
        url: "#",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "90",
    text: "设备管理",
    description: "",
    url: "",
    iconCls: "DesktopOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "9001",
        text: "渠道管理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "9002",
        text: "版本管理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "9003",
        text: "设备在线",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "9004",
        text: "设备统计",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "70",
    text: "地区管理",
    description: "",
    url: "",
    iconCls: "AimOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "7001",
        text: "国家管理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "7002",
        text: "州管理",
        description: "州/省管理",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }, {
        id: "7003",
        text: "城市管理",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }, {
    id: "99",
    text: "系统管理",
    description: "",
    url: "",
    iconCls: "SettingOutlined",
    role: [],
    activeName: "buyPlan",
    children: [
      {
        id: "9901",
        text: "系统配置",
        description: "",
        url: "http://www.baidu.com",
        iconCls: "fa-user-circle-o",
        role: [],
        activeName: "buyPlan"
      }
    ]
  }
];
